# System
if(CMAKE_SYSTEM_NAME MATCHES "^Windows")
    set(SYSTEM.Windows 1)
    add_definitions(-DCOOKIE_SYSTEM_WINDOWS)
elseif(CMAKE_SYSTEM_NAME MATCHES "^Linux")
    set(SYSTEM.Linux 1)
    add_definitions(-DCOOKIE_SYSTEM_LINUX)
elseif(CMAKE_SYSTEM_NAME MATCHES "^Darwin")
    set(SYSTEM.MacOS 1)
    add_definitions(-DCOOKIE_SYSTEM_MACOS)
elseif(CMAKE_SYSTEM_NAME MATCHES "^Android")
    set(SYSTEM.Android 1)
    add_definitions(-DCOOKIE_SYSTEM_ANDROID)
elseif(CMAKE_SYSTEM_NAME MATCHES "^iOS")
    set(SYSTEM.iOS 1)
    add_definitions(-DCOOKIE_SYSTEM_IOS)
endif()

# Arch
if(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "AMD64")
    set(ARCH.X86_64 1)
    set(COOKIE_BOOST_ARCH_NAME "x86_64")
    add_definitions(-DCOOKIE_ARCH_X86_64)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "i[3-6]86")
    set(ARCH.X86 1)
    set(COOKIE_BOOST_ARCH_NAME "x86")
    add_definitions(-DCOOKIE_ARCH_X86)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "armv7l" OR CMAKE_SYSTEM_PROCESSOR MATCHES "armv8l")
    set(ARCH.ARM32 1)
    if(SYSTEM.Android)
        set(COOKIE_BOOST_ARCH_NAME "armeabi-v7a")
    endif()
    add_definitions(-DCOOKIE_ARCH_ARM32)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "arm64")
    set(ARCH.ARM64 1)
    if(SYSTEM.Android)
        set(COOKIE_BOOST_ARCH_NAME "arm64-v8a")
    endif()
    add_definitions(-DCOOKIE_ARCH_ARM64)
endif()